### ISSUE TITLE
[質問] poetry install でPyTorchがinstall できない

### ISSUE THREAD

**Issue by 223mle** [hppRC/bert-classification-tutorial#1]
お忙しいところ失礼します。
poetry installを行った際、Installing torchで失敗してしまいます。
色々試してみましたが、解決できなかったので、可能であれば解決方法を教えて欲しいです。
大変恐縮ですが、よろしくお願いします。

[環境]
M2 Macbook Air 

[試したこと]
pip install torchでtorchをダウンロードできるか確認。-> できました。
エラー文で検索。 -> 恐らく自分の環境とPyTorchの環境が合っていない？
自分の環境に合ったPyTorchのversionの探し方がわからず、断念。

[エラー文]
Package operations: 1 install, 0 updates, 0 removals

  • Installing torch (1.13.0+cu116 https://download.pytorch.org/whl/cu116/torch-1.13.0%2Bcu116-cp310-cp310-linux_x86_64.whl): Failed

  CalledProcessError

  Command '['/Users/daikitsutsumi/BERT_tutorial/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/daikitsutsumi/BERT_tutorial/.venv', '--no-deps', '/Users/daikitsutsumi/Library/Caches/pypoetry/artifacts/a6/00/dc/7f88cdf8d7e62945ee8e80cd81d738f927b5dd55452d1e517bea8de8b8/torch-1.13.0+cu116-cp310-cp310-linux_x86_64.whl']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:571 in run
       567│             # We don't call process.wait() as .__exit__ does that for us.
       568│             raise
       569│         retcode = process.poll()
       570│         if check and retcode:
    →  571│             raise CalledProcessError(retcode, process.args,
       572│                                      output=stdout, stderr=stderr)
       573│     return CompletedProcess(process.args, retcode, stdout, stderr)
       574│ 
       575│ 

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['/Users/daikitsutsumi/BERT_tutorial/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/daikitsutsumi/BERT_tutorial/.venv', '--no-deps', '/Users/daikitsutsumi/Library/Caches/pypoetry/artifacts/a6/00/dc/7f88cdf8d7e62945ee8e80cd81d738f927b5dd55452d1e517bea8de8b8/torch-1.13.0+cu116-cp310-cp310-linux_x86_64.whl'] errored with the following return code 1, and output: 
  ERROR: torch-1.13.0+cu116-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
  

  at /opt/homebrew/Cellar/poetry/1.3.1/libexec/lib/python3.11/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:

  PoetryException

  Failed to install /Users/daikitsutsumi/Library/Caches/pypoetry/artifacts/a6/00/dc/7f88cdf8d7e62945ee8e80cd81d738f927b5dd55452d1e517bea8de8b8/torch-1.13.0+cu116-cp310-cp310-linux_x86_64.whl

  at /opt/homebrew/Cellar/poetry/1.3.1/libexec/lib/python3.11/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│

**Comment by hppRC** [comment]
@tsutsumi-ozro 
丁寧なご質問ありがとうございます！
原因はおそらく調べていただいた内容の通りで、M1 Macbook Airに備わっているGPUと、本リポジトリのPyTorchが想定しているGPUが異なるので、エラーが出ている、という感じだと思います。
本リポジトリは主にNVIDIAのGPUを備えたLinuxサーバでの実行を想定しています(README.mdに後ほど追記しておきます)が、M1 Macbook AirでPoetryを用いて動作させるのは少し難しいかもしれません。

そこで、よければ以下のどちらかを試してみていただけますと幸いです:
- M1 MacbookでPyTorchをインストールする[こちらの記事](https://zenn.dev/hidetoshi/articles/20220731_pytorch-m1-macbook-gpu)のように、`conda`と`pip`でインストール&実行
- [こちらの記事](https://zenn.dev/zzz/articles/970e5df5cf1f65)のように、 Google ColaboratoryなどM1 Macbook以外の環境で、pipなどを利用してインストール&実行

もしエラーが解決しましたら、どのように解決したかを記載していただけますと大変参考になります。
どうぞよろしくお願いします 🙇

**Comment by 223mle** [comment]
ご丁寧な回答ありがとうございます。
[ご提案されたこちらの記事](https://zenn.dev/hidetoshi/articles/20220731_pytorch-m1-macbook-gpu)に沿ってinstallしたところ正常に動きました🙇‍♂️
